export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const DELETE_USER = 'DELETE_USER'

export const ADD_WATCH = 'ADD_WATCH'
export const GET_COMICS = 'GET_COMICS'
export const SEARCH_COMICS = 'SEARCH_COMICS'
export const RESET_COMICS = 'RESET_COMICS'
export const RESET_SEARCH_FAILED = 'RESET_SEARCH_FAILED'
export const CLEAR_COMICS = 'CLEAR_COMICS'
export const DELETE_WATCH = 'DELETE_WATCH' 

export const SORT_COMICS = 'SORT_COMICS'
export const RESET_SORT = 'RESET_SORT'
export const WATCH_MAKER_SORT = 'Watch Maker'
export const WATCH_NAME_SORT = 'Watch Name'
export const NEWEST_TO_OLDEST_SORT = 'Newest to Oldest'
export const OLDEST_TO_NEWEST_SORT = 'Oldest to Newest'
export const COST_LOW_TO_HIGH_SORT = 'Cost Low to High'
export const COST_HIGH_TO_LOW_SORT = 'Cost High to Low'